/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

using System;
using System.Text;
using Thrift.Protocol;

#if !SILVERLIGHT

[Serializable]
#endif
public partial class Address : TBase
{
    private string _city;
    private string _street;

    public string City
    {
        get
        {
            return _city;
        }
        set
        {
            __isset.city = true;
            this._city = value;
        }
    }

    public string Street
    {
        get
        {
            return _street;
        }
        set
        {
            __isset.street = true;
            this._street = value;
        }
    }


    public Isset __isset;
#if !SILVERLIGHT
    [Serializable]
#endif
    public struct Isset
    {
        public bool city;
        public bool street;
    }

    public Address()
    {
    }

    public void Read(TProtocol iprot)
    {
        iprot.IncrementRecursionDepth();
        try
        {
            TField field;
            iprot.ReadStructBegin();
            while (true)
            {
                field = iprot.ReadFieldBegin();
                if (field.Type == TType.Stop)
                {
                    break;
                }
                switch (field.ID)
                {
                    case 1:
                        if (field.Type == TType.String)
                        {
                            City = iprot.ReadString();
                        }
                        else
                        {
                            TProtocolUtil.Skip(iprot, field.Type);
                        }
                        break;
                    case 2:
                        if (field.Type == TType.String)
                        {
                            Street = iprot.ReadString();
                        }
                        else
                        {
                            TProtocolUtil.Skip(iprot, field.Type);
                        }
                        break;
                    default:
                        TProtocolUtil.Skip(iprot, field.Type);
                        break;
                }
                iprot.ReadFieldEnd();
            }
            iprot.ReadStructEnd();
        }
        finally
        {
            iprot.DecrementRecursionDepth();
        }
    }

    public void Write(TProtocol oprot)
    {
        oprot.IncrementRecursionDepth();
        try
        {
            TStruct struc = new TStruct("Address");
            oprot.WriteStructBegin(struc);
            TField field = new TField();
            if (City != null && __isset.city)
            {
                field.Name = "city";
                field.Type = TType.String;
                field.ID = 1;
                oprot.WriteFieldBegin(field);
                oprot.WriteString(City);
                oprot.WriteFieldEnd();
            }
            if (Street != null && __isset.street)
            {
                field.Name = "street";
                field.Type = TType.String;
                field.ID = 2;
                oprot.WriteFieldBegin(field);
                oprot.WriteString(Street);
                oprot.WriteFieldEnd();
            }
            oprot.WriteFieldStop();
            oprot.WriteStructEnd();
        }
        finally
        {
            oprot.DecrementRecursionDepth();
        }
    }

    public override string ToString()
    {
        StringBuilder __sb = new StringBuilder("Address(");
        bool __first = true;
        if (City != null && __isset.city)
        {
            if (!__first) { __sb.Append(", "); }
            __first = false;
            __sb.Append("City: ");
            __sb.Append(City);
        }
        if (Street != null && __isset.street)
        {
            if (!__first) { __sb.Append(", "); }
            __first = false;
            __sb.Append("Street: ");
            __sb.Append(Street);
        }
        __sb.Append(")");
        return __sb.ToString();
    }

}


