/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

using System;
using System.Text;
using Thrift.Protocol;

#if !SILVERLIGHT

    [Serializable]
#endif
    public partial class Customer : TBase
    {
        private int _customerId;
        private string _name;
        private Address _addressInfo;

        public int CustomerId
        {
            get
            {
                return _customerId;
            }
            set
            {
                __isset.customerId = true;
                this._customerId = value;
            }
        }

        public string Name
        {
            get
            {
                return _name;
            }
            set
            {
                __isset.name = true;
                this._name = value;
            }
        }

        public Address AddressInfo
        {
            get
            {
                return _addressInfo;
            }
            set
            {
                __isset.addressInfo = true;
                this._addressInfo = value;
            }
        }


        public Isset __isset;
#if !SILVERLIGHT
        [Serializable]
#endif
        public struct Isset {
            public bool customerId;
            public bool name;
            public bool addressInfo;
        }

        public Customer() {
        }

        public void Read (TProtocol iprot)
        {
            iprot.IncrementRecursionDepth();
            try
            {
                TField field;
                iprot.ReadStructBegin();
                while (true)
                {
                    field = iprot.ReadFieldBegin();
                    if (field.Type == TType.Stop) { 
                        break;
                    }
                    switch (field.ID)
                    {
                        case 1:
                            if (field.Type == TType.I32) {
                                CustomerId = iprot.ReadI32();
                            } else { 
                                TProtocolUtil.Skip(iprot, field.Type);
                            }
                            break;
                        case 2:
                            if (field.Type == TType.String) {
                                Name = iprot.ReadString();
                            } else { 
                                TProtocolUtil.Skip(iprot, field.Type);
                            }
                            break;
                        case 3:
                            if (field.Type == TType.Struct) {
                                AddressInfo = new Address();
                                AddressInfo.Read(iprot);
                            } else { 
                                TProtocolUtil.Skip(iprot, field.Type);
                            }
                            break;
                        default: 
                            TProtocolUtil.Skip(iprot, field.Type);
                            break;
                    }
                    iprot.ReadFieldEnd();
                }
                iprot.ReadStructEnd();
            }
            finally
            {
                iprot.DecrementRecursionDepth();
            }
        }

        public void Write(TProtocol oprot) {
            oprot.IncrementRecursionDepth();
            try
            {
                TStruct struc = new TStruct("Customer");
                oprot.WriteStructBegin(struc);
                TField field = new TField();
                if (__isset.customerId) {
                    field.Name = "customerId";
                    field.Type = TType.I32;
                    field.ID = 1;
                    oprot.WriteFieldBegin(field);
                    oprot.WriteI32(CustomerId);
                    oprot.WriteFieldEnd();
                }
                if (Name != null && __isset.name) {
                    field.Name = "name";
                    field.Type = TType.String;
                    field.ID = 2;
                    oprot.WriteFieldBegin(field);
                    oprot.WriteString(Name);
                    oprot.WriteFieldEnd();
                }
                if (AddressInfo != null && __isset.addressInfo) {
                    field.Name = "addressInfo";
                    field.Type = TType.Struct;
                    field.ID = 3;
                    oprot.WriteFieldBegin(field);
                    AddressInfo.Write(oprot);
                    oprot.WriteFieldEnd();
                }
                oprot.WriteFieldStop();
                oprot.WriteStructEnd();
            }
            finally
            {
                oprot.DecrementRecursionDepth();
            }
        }

        public override string ToString() {
            StringBuilder __sb = new StringBuilder("Customer(");
            bool __first = true;
            if (__isset.customerId) {
                if(!__first) { __sb.Append(", "); }
                __first = false;
                __sb.Append("CustomerId: ");
                __sb.Append(CustomerId);
            }
            if (Name != null && __isset.name) {
                if(!__first) { __sb.Append(", "); }
                __first = false;
                __sb.Append("Name: ");
                __sb.Append(Name);
            }
            if (AddressInfo != null && __isset.addressInfo) {
                if(!__first) { __sb.Append(", "); }
                __first = false;
                __sb.Append("AddressInfo: ");
                __sb.Append(AddressInfo);
            }
            __sb.Append(")");
            return __sb.ToString();
        }

    }


