/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using Thrift;
using Thrift.Protocol;

 
    public partial class ThriftCustomerService {
        public interface Iface {
            int @Add(Customer customer);
#if SILVERLIGHT
    IAsyncResult Begin_Add(AsyncCallback callback, object state, Customer customer);
    int End_Add(IAsyncResult asyncResult);
    #endif
            Customer @Get(int id);
#if SILVERLIGHT
    IAsyncResult Begin_Get(AsyncCallback callback, object state, int id);
    Customer End_Get(IAsyncResult asyncResult);
    #endif
            List<Customer> GetList();
#if SILVERLIGHT
    IAsyncResult Begin_GetList(AsyncCallback callback, object state);
    List<Customer> End_GetList(IAsyncResult asyncResult);
    #endif
            Dictionary<int, Customer> GetMap();
#if SILVERLIGHT
    IAsyncResult Begin_GetMap(AsyncCallback callback, object state);
    Dictionary<int, Customer> End_GetMap(IAsyncResult asyncResult);
    #endif
        }

        public class Client : IDisposable, Iface {
            public Client(TProtocol prot) : this(prot, prot)
            {
            }

            public Client(TProtocol iprot, TProtocol oprot)
            {
                iprot_ = iprot;
                oprot_ = oprot;
            }

            protected TProtocol iprot_;
            protected TProtocol oprot_;
            protected int seqid_;

            public TProtocol InputProtocol
            {
                get { return iprot_; }
            }
            public TProtocol OutputProtocol
            {
                get { return oprot_; }
            }


            #region " IDisposable Support "
            private bool _IsDisposed;

            // IDisposable
            public void Dispose()
            {
                Dispose(true);
            }
    

            protected virtual void Dispose(bool disposing)
            {
                if (!_IsDisposed)
                {
                    if (disposing)
                    {
                        if (iprot_ != null)
                        {
                            ((IDisposable)iprot_).Dispose();
                        }
                        if (oprot_ != null)
                        {
                            ((IDisposable)oprot_).Dispose();
                        }
                    }
                }
                _IsDisposed = true;
            }
            #endregion


    
#if SILVERLIGHT
    public IAsyncResult Begin_Add(AsyncCallback callback, object state, Customer customer)
    {
      return send_Add(callback, state, customer);
    }

    public int End_Add(IAsyncResult asyncResult)
    {
      oprot_.Transport.EndFlush(asyncResult);
      return recv_Add();
    }

    #endif

            public int @Add(Customer customer)
            {
#if !SILVERLIGHT
                send_Add(customer);
                return recv_Add();

#else
      var asyncResult = Begin_Add(null, null, customer);
      return End_Add(asyncResult);

      #endif
            }
#if SILVERLIGHT
    public IAsyncResult send_Add(AsyncCallback callback, object state, Customer customer)
    #else
            public void send_Add(Customer customer)
#endif
            {
                oprot_.WriteMessageBegin(new TMessage("Add", TMessageType.Call, seqid_));
                Add_args args = new Add_args();
                args.Customer = customer;
                args.Write(oprot_);
                oprot_.WriteMessageEnd();
#if SILVERLIGHT
      return oprot_.Transport.BeginFlush(callback, state);
      #else
                oprot_.Transport.Flush();
#endif
            }

            public int recv_Add()
            {
                TMessage msg = iprot_.ReadMessageBegin();
                if (msg.Type == TMessageType.Exception) {
                    TApplicationException x = TApplicationException.Read(iprot_);
                    iprot_.ReadMessageEnd();
                    throw x;
                }
                Add_result result = new Add_result();
                result.Read(iprot_);
                iprot_.ReadMessageEnd();
                if (result.__isset.success) {
                    return result.Success;
                }
                throw new TApplicationException(TApplicationException.ExceptionType.MissingResult, "Add failed: unknown result");
            }

    
#if SILVERLIGHT
    public IAsyncResult Begin_Get(AsyncCallback callback, object state, int id)
    {
      return send_Get(callback, state, id);
    }

    public Customer End_Get(IAsyncResult asyncResult)
    {
      oprot_.Transport.EndFlush(asyncResult);
      return recv_Get();
    }

    #endif

            public Customer @Get(int id)
            {
#if !SILVERLIGHT
                send_Get(id);
                return recv_Get();

#else
      var asyncResult = Begin_Get(null, null, id);
      return End_Get(asyncResult);

      #endif
            }
#if SILVERLIGHT
    public IAsyncResult send_Get(AsyncCallback callback, object state, int id)
    #else
            public void send_Get(int id)
#endif
            {
                oprot_.WriteMessageBegin(new TMessage("Get", TMessageType.Call, seqid_));
                Get_args args = new Get_args();
                args.Id = id;
                args.Write(oprot_);
                oprot_.WriteMessageEnd();
#if SILVERLIGHT
      return oprot_.Transport.BeginFlush(callback, state);
      #else
                oprot_.Transport.Flush();
#endif
            }

            public Customer recv_Get()
            {
                TMessage msg = iprot_.ReadMessageBegin();
                if (msg.Type == TMessageType.Exception) {
                    TApplicationException x = TApplicationException.Read(iprot_);
                    iprot_.ReadMessageEnd();
                    throw x;
                }
                Get_result result = new Get_result();
                result.Read(iprot_);
                iprot_.ReadMessageEnd();
                if (result.__isset.success) {
                    return result.Success;
                }
                throw new TApplicationException(TApplicationException.ExceptionType.MissingResult, "Get failed: unknown result");
            }

    
#if SILVERLIGHT
    public IAsyncResult Begin_GetList(AsyncCallback callback, object state)
    {
      return send_GetList(callback, state);
    }

    public List<Customer> End_GetList(IAsyncResult asyncResult)
    {
      oprot_.Transport.EndFlush(asyncResult);
      return recv_GetList();
    }

    #endif

            public List<Customer> GetList()
            {
#if !SILVERLIGHT
                send_GetList();
                return recv_GetList();

#else
      var asyncResult = Begin_GetList(null, null);
      return End_GetList(asyncResult);

      #endif
            }
#if SILVERLIGHT
    public IAsyncResult send_GetList(AsyncCallback callback, object state)
    #else
            public void send_GetList()
#endif
            {
                oprot_.WriteMessageBegin(new TMessage("GetList", TMessageType.Call, seqid_));
                GetList_args args = new GetList_args();
                args.Write(oprot_);
                oprot_.WriteMessageEnd();
#if SILVERLIGHT
      return oprot_.Transport.BeginFlush(callback, state);
      #else
                oprot_.Transport.Flush();
#endif
            }

            public List<Customer> recv_GetList()
            {
                TMessage msg = iprot_.ReadMessageBegin();
                if (msg.Type == TMessageType.Exception) {
                    TApplicationException x = TApplicationException.Read(iprot_);
                    iprot_.ReadMessageEnd();
                    throw x;
                }
                GetList_result result = new GetList_result();
                result.Read(iprot_);
                iprot_.ReadMessageEnd();
                if (result.__isset.success) {
                    return result.Success;
                }
                throw new TApplicationException(TApplicationException.ExceptionType.MissingResult, "GetList failed: unknown result");
            }

    
#if SILVERLIGHT
    public IAsyncResult Begin_GetMap(AsyncCallback callback, object state)
    {
      return send_GetMap(callback, state);
    }

    public Dictionary<int, Customer> End_GetMap(IAsyncResult asyncResult)
    {
      oprot_.Transport.EndFlush(asyncResult);
      return recv_GetMap();
    }

    #endif

            public Dictionary<int, Customer> GetMap()
            {
#if !SILVERLIGHT
                send_GetMap();
                return recv_GetMap();

#else
      var asyncResult = Begin_GetMap(null, null);
      return End_GetMap(asyncResult);

      #endif
            }
#if SILVERLIGHT
    public IAsyncResult send_GetMap(AsyncCallback callback, object state)
    #else
            public void send_GetMap()
#endif
            {
                oprot_.WriteMessageBegin(new TMessage("GetMap", TMessageType.Call, seqid_));
                GetMap_args args = new GetMap_args();
                args.Write(oprot_);
                oprot_.WriteMessageEnd();
#if SILVERLIGHT
      return oprot_.Transport.BeginFlush(callback, state);
      #else
                oprot_.Transport.Flush();
#endif
            }

            public Dictionary<int, Customer> recv_GetMap()
            {
                TMessage msg = iprot_.ReadMessageBegin();
                if (msg.Type == TMessageType.Exception) {
                    TApplicationException x = TApplicationException.Read(iprot_);
                    iprot_.ReadMessageEnd();
                    throw x;
                }
                GetMap_result result = new GetMap_result();
                result.Read(iprot_);
                iprot_.ReadMessageEnd();
                if (result.__isset.success) {
                    return result.Success;
                }
                throw new TApplicationException(TApplicationException.ExceptionType.MissingResult, "GetMap failed: unknown result");
            }

        }
        public class Processor : TProcessor {
            public Processor(Iface iface)
            {
                iface_ = iface;
                processMap_["Add"] = Add_Process;
                processMap_["Get"] = Get_Process;
                processMap_["GetList"] = GetList_Process;
                processMap_["GetMap"] = GetMap_Process;
            }

            protected delegate void ProcessFunction(int seqid, TProtocol iprot, TProtocol oprot);
            private Iface iface_;
            protected Dictionary<string, ProcessFunction> processMap_ = new Dictionary<string, ProcessFunction>();

            public bool Process(TProtocol iprot, TProtocol oprot)
            {
                try
                {
                    TMessage msg = iprot.ReadMessageBegin();
                    ProcessFunction fn;
                    processMap_.TryGetValue(msg.Name, out fn);
                    if (fn == null) {
                        TProtocolUtil.Skip(iprot, TType.Struct);
                        iprot.ReadMessageEnd();
                        TApplicationException x = new TApplicationException (TApplicationException.ExceptionType.UnknownMethod, "Invalid method name: '" + msg.Name + "'");
                        oprot.WriteMessageBegin(new TMessage(msg.Name, TMessageType.Exception, msg.SeqID));
                        x.Write(oprot);
                        oprot.WriteMessageEnd();
                        oprot.Transport.Flush();
                        return true;
                    }
                    fn(msg.SeqID, iprot, oprot);
                }
                catch (IOException)
                {
                    return false;
                }
                return true;
            }

            public void Add_Process(int seqid, TProtocol iprot, TProtocol oprot)
            {
                Add_args args = new Add_args();
                args.Read(iprot);
                iprot.ReadMessageEnd();
                Add_result result = new Add_result();
                result.Success = iface_.@Add(args.Customer);
                oprot.WriteMessageBegin(new TMessage("Add", TMessageType.Reply, seqid)); 
                result.Write(oprot);
                oprot.WriteMessageEnd();
                oprot.Transport.Flush();
            }

            public void Get_Process(int seqid, TProtocol iprot, TProtocol oprot)
            {
                Get_args args = new Get_args();
                args.Read(iprot);
                iprot.ReadMessageEnd();
                Get_result result = new Get_result();
                result.Success = iface_.@Get(args.Id);
                oprot.WriteMessageBegin(new TMessage("Get", TMessageType.Reply, seqid)); 
                result.Write(oprot);
                oprot.WriteMessageEnd();
                oprot.Transport.Flush();
            }

            public void GetList_Process(int seqid, TProtocol iprot, TProtocol oprot)
            {
                GetList_args args = new GetList_args();
                args.Read(iprot);
                iprot.ReadMessageEnd();
                GetList_result result = new GetList_result();
                result.Success = iface_.GetList();
                oprot.WriteMessageBegin(new TMessage("GetList", TMessageType.Reply, seqid)); 
                result.Write(oprot);
                oprot.WriteMessageEnd();
                oprot.Transport.Flush();
            }

            public void GetMap_Process(int seqid, TProtocol iprot, TProtocol oprot)
            {
                GetMap_args args = new GetMap_args();
                args.Read(iprot);
                iprot.ReadMessageEnd();
                GetMap_result result = new GetMap_result();
                result.Success = iface_.GetMap();
                oprot.WriteMessageBegin(new TMessage("GetMap", TMessageType.Reply, seqid)); 
                result.Write(oprot);
                oprot.WriteMessageEnd();
                oprot.Transport.Flush();
            }

        }


#if !SILVERLIGHT
        [Serializable]
#endif
        public partial class Add_args : TBase
        {
            private Customer _customer;

            public Customer Customer
            {
                get
                {
                    return _customer;
                }
                set
                {
                    __isset.customer = true;
                    this._customer = value;
                }
            }


            public Isset __isset;
#if !SILVERLIGHT
            [Serializable]
#endif
            public struct Isset {
                public bool customer;
            }

            public Add_args() {
            }

            public void Read (TProtocol iprot)
            {
                iprot.IncrementRecursionDepth();
                try
                {
                    TField field;
                    iprot.ReadStructBegin();
                    while (true)
                    {
                        field = iprot.ReadFieldBegin();
                        if (field.Type == TType.Stop) { 
                            break;
                        }
                        switch (field.ID)
                        {
                            case 1:
                                if (field.Type == TType.Struct) {
                                    Customer = new Customer();
                                    Customer.Read(iprot);
                                } else { 
                                    TProtocolUtil.Skip(iprot, field.Type);
                                }
                                break;
                            default: 
                                TProtocolUtil.Skip(iprot, field.Type);
                                break;
                        }
                        iprot.ReadFieldEnd();
                    }
                    iprot.ReadStructEnd();
                }
                finally
                {
                    iprot.DecrementRecursionDepth();
                }
            }

            public void Write(TProtocol oprot) {
                oprot.IncrementRecursionDepth();
                try
                {
                    TStruct struc = new TStruct("Add_args");
                    oprot.WriteStructBegin(struc);
                    TField field = new TField();
                    if (Customer != null && __isset.customer) {
                        field.Name = "customer";
                        field.Type = TType.Struct;
                        field.ID = 1;
                        oprot.WriteFieldBegin(field);
                        Customer.Write(oprot);
                        oprot.WriteFieldEnd();
                    }
                    oprot.WriteFieldStop();
                    oprot.WriteStructEnd();
                }
                finally
                {
                    oprot.DecrementRecursionDepth();
                }
            }

            public override string ToString() {
                StringBuilder __sb = new StringBuilder("Add_args(");
                bool __first = true;
                if (Customer != null && __isset.customer) {
                    if(!__first) { __sb.Append(", "); }
                    __first = false;
                    __sb.Append("Customer: ");
                    __sb.Append(Customer== null ? "<null>" : Customer.ToString());
                }
                __sb.Append(")");
                return __sb.ToString();
            }

        }


#if !SILVERLIGHT
        [Serializable]
#endif
        public partial class Add_result : TBase
        {
            private int _success;

            public int Success
            {
                get
                {
                    return _success;
                }
                set
                {
                    __isset.success = true;
                    this._success = value;
                }
            }


            public Isset __isset;
#if !SILVERLIGHT
            [Serializable]
#endif
            public struct Isset {
                public bool success;
            }

            public Add_result() {
            }

            public void Read (TProtocol iprot)
            {
                iprot.IncrementRecursionDepth();
                try
                {
                    TField field;
                    iprot.ReadStructBegin();
                    while (true)
                    {
                        field = iprot.ReadFieldBegin();
                        if (field.Type == TType.Stop) { 
                            break;
                        }
                        switch (field.ID)
                        {
                            case 0:
                                if (field.Type == TType.I32) {
                                    Success = iprot.ReadI32();
                                } else { 
                                    TProtocolUtil.Skip(iprot, field.Type);
                                }
                                break;
                            default: 
                                TProtocolUtil.Skip(iprot, field.Type);
                                break;
                        }
                        iprot.ReadFieldEnd();
                    }
                    iprot.ReadStructEnd();
                }
                finally
                {
                    iprot.DecrementRecursionDepth();
                }
            }

            public void Write(TProtocol oprot) {
                oprot.IncrementRecursionDepth();
                try
                {
                    TStruct struc = new TStruct("Add_result");
                    oprot.WriteStructBegin(struc);
                    TField field = new TField();

                    if (this.__isset.success) {
                        field.Name = "Success";
                        field.Type = TType.I32;
                        field.ID = 0;
                        oprot.WriteFieldBegin(field);
                        oprot.WriteI32(Success);
                        oprot.WriteFieldEnd();
                    }
                    oprot.WriteFieldStop();
                    oprot.WriteStructEnd();
                }
                finally
                {
                    oprot.DecrementRecursionDepth();
                }
            }

            public override string ToString() {
                StringBuilder __sb = new StringBuilder("Add_result(");
                bool __first = true;
                if (__isset.success) {
                    if(!__first) { __sb.Append(", "); }
                    __first = false;
                    __sb.Append("Success: ");
                    __sb.Append(Success);
                }
                __sb.Append(")");
                return __sb.ToString();
            }

        }


#if !SILVERLIGHT
        [Serializable]
#endif
        public partial class Get_args : TBase
        {
            private int _id;

            public int Id
            {
                get
                {
                    return _id;
                }
                set
                {
                    __isset.id = true;
                    this._id = value;
                }
            }


            public Isset __isset;
#if !SILVERLIGHT
            [Serializable]
#endif
            public struct Isset {
                public bool id;
            }

            public Get_args() {
            }

            public void Read (TProtocol iprot)
            {
                iprot.IncrementRecursionDepth();
                try
                {
                    TField field;
                    iprot.ReadStructBegin();
                    while (true)
                    {
                        field = iprot.ReadFieldBegin();
                        if (field.Type == TType.Stop) { 
                            break;
                        }
                        switch (field.ID)
                        {
                            case 1:
                                if (field.Type == TType.I32) {
                                    Id = iprot.ReadI32();
                                } else { 
                                    TProtocolUtil.Skip(iprot, field.Type);
                                }
                                break;
                            default: 
                                TProtocolUtil.Skip(iprot, field.Type);
                                break;
                        }
                        iprot.ReadFieldEnd();
                    }
                    iprot.ReadStructEnd();
                }
                finally
                {
                    iprot.DecrementRecursionDepth();
                }
            }

            public void Write(TProtocol oprot) {
                oprot.IncrementRecursionDepth();
                try
                {
                    TStruct struc = new TStruct("Get_args");
                    oprot.WriteStructBegin(struc);
                    TField field = new TField();
                    if (__isset.id) {
                        field.Name = "id";
                        field.Type = TType.I32;
                        field.ID = 1;
                        oprot.WriteFieldBegin(field);
                        oprot.WriteI32(Id);
                        oprot.WriteFieldEnd();
                    }
                    oprot.WriteFieldStop();
                    oprot.WriteStructEnd();
                }
                finally
                {
                    oprot.DecrementRecursionDepth();
                }
            }

            public override string ToString() {
                StringBuilder __sb = new StringBuilder("Get_args(");
                bool __first = true;
                if (__isset.id) {
                    if(!__first) { __sb.Append(", "); }
                    __first = false;
                    __sb.Append("Id: ");
                    __sb.Append(Id);
                }
                __sb.Append(")");
                return __sb.ToString();
            }

        }


#if !SILVERLIGHT
        [Serializable]
#endif
        public partial class Get_result : TBase
        {
            private Customer _success;

            public Customer Success
            {
                get
                {
                    return _success;
                }
                set
                {
                    __isset.success = true;
                    this._success = value;
                }
            }


            public Isset __isset;
#if !SILVERLIGHT
            [Serializable]
#endif
            public struct Isset {
                public bool success;
            }

            public Get_result() {
            }

            public void Read (TProtocol iprot)
            {
                iprot.IncrementRecursionDepth();
                try
                {
                    TField field;
                    iprot.ReadStructBegin();
                    while (true)
                    {
                        field = iprot.ReadFieldBegin();
                        if (field.Type == TType.Stop) { 
                            break;
                        }
                        switch (field.ID)
                        {
                            case 0:
                                if (field.Type == TType.Struct) {
                                    Success = new Customer();
                                    Success.Read(iprot);
                                } else { 
                                    TProtocolUtil.Skip(iprot, field.Type);
                                }
                                break;
                            default: 
                                TProtocolUtil.Skip(iprot, field.Type);
                                break;
                        }
                        iprot.ReadFieldEnd();
                    }
                    iprot.ReadStructEnd();
                }
                finally
                {
                    iprot.DecrementRecursionDepth();
                }
            }

            public void Write(TProtocol oprot) {
                oprot.IncrementRecursionDepth();
                try
                {
                    TStruct struc = new TStruct("Get_result");
                    oprot.WriteStructBegin(struc);
                    TField field = new TField();

                    if (this.__isset.success) {
                        if (Success != null) {
                            field.Name = "Success";
                            field.Type = TType.Struct;
                            field.ID = 0;
                            oprot.WriteFieldBegin(field);
                            Success.Write(oprot);
                            oprot.WriteFieldEnd();
                        }
                    }
                    oprot.WriteFieldStop();
                    oprot.WriteStructEnd();
                }
                finally
                {
                    oprot.DecrementRecursionDepth();
                }
            }

            public override string ToString() {
                StringBuilder __sb = new StringBuilder("Get_result(");
                bool __first = true;
                if (Success != null && __isset.success) {
                    if(!__first) { __sb.Append(", "); }
                    __first = false;
                    __sb.Append("Success: ");
                    __sb.Append(Success== null ? "<null>" : Success.ToString());
                }
                __sb.Append(")");
                return __sb.ToString();
            }

        }


#if !SILVERLIGHT
        [Serializable]
#endif
        public partial class GetList_args : TBase
        {

            public GetList_args() {
            }

            public void Read (TProtocol iprot)
            {
                iprot.IncrementRecursionDepth();
                try
                {
                    TField field;
                    iprot.ReadStructBegin();
                    while (true)
                    {
                        field = iprot.ReadFieldBegin();
                        if (field.Type == TType.Stop) { 
                            break;
                        }
                        switch (field.ID)
                        {
                            default: 
                                TProtocolUtil.Skip(iprot, field.Type);
                                break;
                        }
                        iprot.ReadFieldEnd();
                    }
                    iprot.ReadStructEnd();
                }
                finally
                {
                    iprot.DecrementRecursionDepth();
                }
            }

            public void Write(TProtocol oprot) {
                oprot.IncrementRecursionDepth();
                try
                {
                    TStruct struc = new TStruct("GetList_args");
                    oprot.WriteStructBegin(struc);
                    oprot.WriteFieldStop();
                    oprot.WriteStructEnd();
                }
                finally
                {
                    oprot.DecrementRecursionDepth();
                }
            }

            public override string ToString() {
                StringBuilder __sb = new StringBuilder("GetList_args(");
                __sb.Append(")");
                return __sb.ToString();
            }

        }


#if !SILVERLIGHT
        [Serializable]
#endif
        public partial class GetList_result : TBase
        {
            private List<Customer> _success;

            public List<Customer> Success
            {
                get
                {
                    return _success;
                }
                set
                {
                    __isset.success = true;
                    this._success = value;
                }
            }


            public Isset __isset;
#if !SILVERLIGHT
            [Serializable]
#endif
            public struct Isset {
                public bool success;
            }

            public GetList_result() {
            }

            public void Read (TProtocol iprot)
            {
                iprot.IncrementRecursionDepth();
                try
                {
                    TField field;
                    iprot.ReadStructBegin();
                    while (true)
                    {
                        field = iprot.ReadFieldBegin();
                        if (field.Type == TType.Stop) { 
                            break;
                        }
                        switch (field.ID)
                        {
                            case 0:
                                if (field.Type == TType.List) {
                                    {
                                        Success = new List<Customer>();
                                        TList _list0 = iprot.ReadListBegin();
                                        for( int _i1 = 0; _i1 < _list0.Count; ++_i1)
                                        {
                                            Customer _elem2;
                                            _elem2 = new Customer();
                                            _elem2.Read(iprot);
                                            Success.Add(_elem2);
                                        }
                                        iprot.ReadListEnd();
                                    }
                                } else { 
                                    TProtocolUtil.Skip(iprot, field.Type);
                                }
                                break;
                            default: 
                                TProtocolUtil.Skip(iprot, field.Type);
                                break;
                        }
                        iprot.ReadFieldEnd();
                    }
                    iprot.ReadStructEnd();
                }
                finally
                {
                    iprot.DecrementRecursionDepth();
                }
            }

            public void Write(TProtocol oprot) {
                oprot.IncrementRecursionDepth();
                try
                {
                    TStruct struc = new TStruct("GetList_result");
                    oprot.WriteStructBegin(struc);
                    TField field = new TField();

                    if (this.__isset.success) {
                        if (Success != null) {
                            field.Name = "Success";
                            field.Type = TType.List;
                            field.ID = 0;
                            oprot.WriteFieldBegin(field);
                            {
                                oprot.WriteListBegin(new TList(TType.Struct, Success.Count));
                                foreach (Customer _iter3 in Success)
                                {
                                    _iter3.Write(oprot);
                                }
                                oprot.WriteListEnd();
                            }
                            oprot.WriteFieldEnd();
                        }
                    }
                    oprot.WriteFieldStop();
                    oprot.WriteStructEnd();
                }
                finally
                {
                    oprot.DecrementRecursionDepth();
                }
            }

            public override string ToString() {
                StringBuilder __sb = new StringBuilder("GetList_result(");
                bool __first = true;
                if (Success != null && __isset.success) {
                    if(!__first) { __sb.Append(", "); }
                    __first = false;
                    __sb.Append("Success: ");
                    __sb.Append(Success);
                }
                __sb.Append(")");
                return __sb.ToString();
            }

        }


#if !SILVERLIGHT
        [Serializable]
#endif
        public partial class GetMap_args : TBase
        {

            public GetMap_args() {
            }

            public void Read (TProtocol iprot)
            {
                iprot.IncrementRecursionDepth();
                try
                {
                    TField field;
                    iprot.ReadStructBegin();
                    while (true)
                    {
                        field = iprot.ReadFieldBegin();
                        if (field.Type == TType.Stop) { 
                            break;
                        }
                        switch (field.ID)
                        {
                            default: 
                                TProtocolUtil.Skip(iprot, field.Type);
                                break;
                        }
                        iprot.ReadFieldEnd();
                    }
                    iprot.ReadStructEnd();
                }
                finally
                {
                    iprot.DecrementRecursionDepth();
                }
            }

            public void Write(TProtocol oprot) {
                oprot.IncrementRecursionDepth();
                try
                {
                    TStruct struc = new TStruct("GetMap_args");
                    oprot.WriteStructBegin(struc);
                    oprot.WriteFieldStop();
                    oprot.WriteStructEnd();
                }
                finally
                {
                    oprot.DecrementRecursionDepth();
                }
            }

            public override string ToString() {
                StringBuilder __sb = new StringBuilder("GetMap_args(");
                __sb.Append(")");
                return __sb.ToString();
            }

        }


#if !SILVERLIGHT
        [Serializable]
#endif
        public partial class GetMap_result : TBase
        {
            private Dictionary<int, Customer> _success;

            public Dictionary<int, Customer> Success
            {
                get
                {
                    return _success;
                }
                set
                {
                    __isset.success = true;
                    this._success = value;
                }
            }


            public Isset __isset;
#if !SILVERLIGHT
            [Serializable]
#endif
            public struct Isset {
                public bool success;
            }

            public GetMap_result() {
            }

            public void Read (TProtocol iprot)
            {
                iprot.IncrementRecursionDepth();
                try
                {
                    TField field;
                    iprot.ReadStructBegin();
                    while (true)
                    {
                        field = iprot.ReadFieldBegin();
                        if (field.Type == TType.Stop) { 
                            break;
                        }
                        switch (field.ID)
                        {
                            case 0:
                                if (field.Type == TType.Map) {
                                    {
                                        Success = new Dictionary<int, Customer>();
                                        TMap _map4 = iprot.ReadMapBegin();
                                        for( int _i5 = 0; _i5 < _map4.Count; ++_i5)
                                        {
                                            int _key6;
                                            Customer _val7;
                                            _key6 = iprot.ReadI32();
                                            _val7 = new Customer();
                                            _val7.Read(iprot);
                                            Success[_key6] = _val7;
                                        }
                                        iprot.ReadMapEnd();
                                    }
                                } else { 
                                    TProtocolUtil.Skip(iprot, field.Type);
                                }
                                break;
                            default: 
                                TProtocolUtil.Skip(iprot, field.Type);
                                break;
                        }
                        iprot.ReadFieldEnd();
                    }
                    iprot.ReadStructEnd();
                }
                finally
                {
                    iprot.DecrementRecursionDepth();
                }
            }

            public void Write(TProtocol oprot) {
                oprot.IncrementRecursionDepth();
                try
                {
                    TStruct struc = new TStruct("GetMap_result");
                    oprot.WriteStructBegin(struc);
                    TField field = new TField();

                    if (this.__isset.success) {
                        if (Success != null) {
                            field.Name = "Success";
                            field.Type = TType.Map;
                            field.ID = 0;
                            oprot.WriteFieldBegin(field);
                            {
                                oprot.WriteMapBegin(new TMap(TType.I32, TType.Struct, Success.Count));
                                foreach (int _iter8 in Success.Keys)
                                {
                                    oprot.WriteI32(_iter8);
                                    Success[_iter8].Write(oprot);
                                }
                                oprot.WriteMapEnd();
                            }
                            oprot.WriteFieldEnd();
                        }
                    }
                    oprot.WriteFieldStop();
                    oprot.WriteStructEnd();
                }
                finally
                {
                    oprot.DecrementRecursionDepth();
                }
            }

            public override string ToString() {
                StringBuilder __sb = new StringBuilder("GetMap_result(");
                bool __first = true;
                if (Success != null && __isset.success) {
                    if(!__first) { __sb.Append(", "); }
                    __first = false;
                    __sb.Append("Success: ");
                    __sb.Append(Success);
                }
                __sb.Append(")");
                return __sb.ToString();
            }

        }

    } 